#!/bin/sh
set -e
IFS=:

TODAY=$(/bin/date "+%Y%m%d")
BACKUP_DEST_FOLDER=${BACKUP_DEST_FOLDER:-/var/tmp/}
BACKUP_DELETE_LOCAL_COPY=${BACKUP_DELETE_LOCAL_COPY:-true}
BACKUP_S3_HOST=${BACKUP_S3_HOST:-s3.amazonaws.com}
BACKUP_S3_HOST_BUCKET=${BACKUP_S3_HOST_BUCKET:-%(bucket)s.s3.amazonaws.com}

if ${BACKUP_NO_SSL}; then
    SSL_OPTION="--no-ssl"
fi

put_file_to_s3(){
    /usr/bin/s3cmd \
        --host="${BACKUP_S3_HOST}" \
        --host-bucket="${BACKUP_S3_HOST_BUCKET}" \
        "${SSL_OPTION}" \
        --access_key="${BACKUP_S3_KEY:?'BACKUP_AWS_KEY is required'}" \
        --secret_key="${BACKUP_S3_SECRET:?'BACKUP_AWS_SECRET is required'}" \
        put "$1" \
        "${BACKUP_S3_PATH}"

    if [ -n "${BACKUP_DELETE_LOCAL_COPY}" ]; then
      rm "$1"
    fi
}

postgre_backup_single() {
    local backup_name="${BACKUP_DEST_FOLDER}${TODAY}_$1_postgredump.sql.gz"
    /usr/bin/pg_dump "$1" | gzip > "${backup_name}"
    put_file_to_s3 "${backup_name}"
}

postgre_backup_all() {
    local backup_name="${BACKUP_DEST_FOLDER}${TODAY}_all_postgredump.sql.gz"
    /usr/bin/pg_dumpall | gzip > "${backup_name}"
    put_file_to_s3 "${backup_name}"
}

if [ -n "${PGHOST}" ]; then
    if [ -n "${DB_NAME}" ]; then
        postgre_backup_single "${DB_NAME}"
    else
        postgre_backup_all
    fi
fi
